package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"strings"
	"time"
)

// Reporter aggregates results and generates reports and test cases
type Reporter struct {
	results []ExecutionResult
}

func NewReporter() *Reporter {
	return &Reporter{}
}

func (r *Reporter) AddResult(res ExecutionResult) {
	r.results = append(r.results, res)
}

func (r *Reporter) AddResults(results []ExecutionResult) {
	r.results = append(r.results, results...)
}

// PrintConsoleSummary prints a rich summary table to terminal
func (r *Reporter) PrintConsoleSummary() {
	total := len(r.results)
	if total == 0 {
		fmt.Println("Không có kết quả nào để báo cáo.")
		return
	}

	passed := 0
	failed := 0
	errorCounts := make(map[ErrorType]int)
	var failedResults []ExecutionResult

	for _, res := range r.results {
		if res.Passed {
			passed++
		} else {
			failed++
			errorCounts[res.ErrorType]++
			failedResults = append(failedResults, res)
		}
	}

	passRate := float64(passed) / float64(total) * 100

	fmt.Println("\n=======================================================")
	fmt.Println("🎋 BAMBOO VIET — BÁO CÁO KẾT QUẢ TỰ ĐỘNG GÕ & FUZZING")
	fmt.Println("=======================================================")
	fmt.Printf("Tổng số ca kiểm thử (Scenarios) : %d\n", total)
	fmt.Printf("✅ Số ca thành công (Passed)     : %d (%.2f%%)\n", passed, passRate)
	fmt.Printf("❌ Số ca thất bại (Failed)       : %d\n", failed)

	if failed > 0 {
		fmt.Println("\n--- Phân loại các lỗi phát hiện được ---")
		for errType, count := range errorCounts {
			fmt.Printf("  • %-30s : %d trường hợp\n", errType, count)
		}

		fmt.Println("\n--- Danh sách chi tiết các ca gõ bị lỗi ---")
		limit := 15
		if len(failedResults) < limit {
			limit = len(failedResults)
		}
		for i := 0; i < limit; i++ {
			f := failedResults[i]
			fmt.Printf("[%d] Chuỗi gõ: %-15s | Mong đợi: %-10s | Thực tế: %-10s | Lỗi: %s\n",
				i+1, f.Scenario.InputSequence, f.Scenario.TargetText, f.ActualOutput, f.ErrorMessage)
		}
		if len(failedResults) > limit {
			fmt.Printf("... và %d ca lỗi khác (xem chi tiết trong docs/fuzz-report.md)\n", len(failedResults)-limit)
		}
	} else {
		fmt.Println("\n🎉 TUYỆT VỜI! Tất cả các ca gõ ngẫu nhiên và biến thể đều vượt qua thành công 100%!")
	}
	fmt.Println("=======================================================")
}

// GenerateMarkdownReport exports a detailed markdown analysis file
func (r *Reporter) GenerateMarkdownReport(filePath string) error {
	var sb strings.Builder
	total := len(r.results)
	passed := 0
	failed := 0
	errorCounts := make(map[ErrorType]int)
	var failedResults []ExecutionResult

	for _, res := range r.results {
		if res.Passed {
			passed++
		} else {
			failed++
			errorCounts[res.ErrorType]++
			failedResults = append(failedResults, res)
		}
	}

	passRate := 0.0
	if total > 0 {
		passRate = float64(passed) / float64(total) * 100
	}

	sb.WriteString("# 🎋 Bamboo Viet — Báo Cáo Fuzzing & Auto-Typing\n\n")
	sb.WriteString(fmt.Sprintf("Thời gian chạy: `%s`\n\n", time.Now().Format("2006-01-02 15:04:05")))
	sb.WriteString("## 1. Tổng Quan\n\n")
	sb.WriteString(fmt.Sprintf("| Chỉ số | Giá trị |\n|---|---|\n"))
	sb.WriteString(fmt.Sprintf("| **Tổng số kịch bản test** | `%d` |\n", total))
	sb.WriteString(fmt.Sprintf("| **Thành công (Passed)** | `%d (%.2f%%)` |\n", passed, passRate))
	sb.WriteString(fmt.Sprintf("| **Thất bại (Failed)** | `%d` |\n\n", failed))

	if failed > 0 {
		sb.WriteString("## 2. Thống Kê Loại Lỗi\n\n")
		sb.WriteString("| Mã Lỗi | Mô tả | Số lượng |\n|---|---|---|\n")
		for errType, count := range errorCounts {
			sb.WriteString(fmt.Sprintf("| `%s` | %s | **%d** |\n", errType, getErrorDescription(errType), count))
		}

		sb.WriteString("\n## 3. Danh Sách Chi Tiết Các Ca Lỗi\n\n")
		sb.WriteString("| STT | Chuỗi phím gõ | Từ mong muốn | Kết quả thực tế | Phân loại lỗi |\n")
		sb.WriteString("|---|---|---|---|---|\n")
		for i, f := range failedResults {
			sb.WriteString(fmt.Sprintf("| %d | `%s` | **%s** | `%s` | `%s` |\n",
				i+1, f.Scenario.InputSequence, f.Scenario.TargetText, f.ActualOutput, f.ErrorType))
		}
	} else {
		sb.WriteString("## 2. Kết Luận\n\n✅ 100% kịch bản gõ thử nghiệm đều cho kết quả chính xác tuyệt đối.\n")
	}

	return ioutil.WriteFile(filePath, []byte(sb.String()), 0644)
}

// GenerateGoTestFile creates an auto-generated Go test file with reproducible test cases
func (r *Reporter) GenerateGoTestFile(filePath string) error {
	var failedResults []ExecutionResult
	for _, res := range r.results {
		if !res.Passed {
			failedResults = append(failedResults, res)
		}
	}

	if len(failedResults) == 0 {
		return nil
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by bamboo-viet-fuzzer. DO NOT EDIT MANUALLY.\n")
	sb.WriteString("package main\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"testing\"\n")
	sb.WriteString("\t\"github.com/BambooEngine/bamboo-core\"\n")
	sb.WriteString(")\n\n")
	sb.WriteString("func TestAutoGeneratedFuzzCases(t *testing.T) {\n")
	sb.WriteString("\timDefs := bamboo.GetInputMethodDefinitions()\n")
	sb.WriteString("\ttelexMethod := bamboo.ParseInputMethod(imDefs, \"Telex\")\n\n")
	sb.WriteString("\ttestCases := []struct {\n")
	sb.WriteString("\t\tname     string\n")
	sb.WriteString("\t\tinput    string\n")
	sb.WriteString("\t\texpected string\n")
	sb.WriteString("\t}{\n")

	for i, f := range failedResults {
		// Clean test name
		testName := fmt.Sprintf("Case_%d_%s", i+1, f.Scenario.InputSequence)
		testName = strings.ReplaceAll(testName, "<BS>", "_BS_")
		testName = strings.ReplaceAll(testName, " ", "_space_")
		sb.WriteString(fmt.Sprintf("\t\t{%q, %q, %q},\n", testName, f.Scenario.InputSequence, f.Scenario.TargetText))
	}

	sb.WriteString("\t}\n\n")
	sb.WriteString("\tfor _, tc := range testCases {\n")
	sb.WriteString("\t\tt.Run(tc.name, func(t *testing.T) {\n")
	sb.WriteString("\t\t\tengine := bamboo.NewEngine(telexMethod, bamboo.EstdFlags)\n")
	sb.WriteString("\t\t\tfor _, r := range tc.input {\n")
	sb.WriteString("\t\t\t\tengine.ProcessKey(r, bamboo.VietnameseMode)\n")
	sb.WriteString("\t\t\t}\n")
	sb.WriteString("\t\t\tactual := engine.GetProcessedString(bamboo.VietnameseMode)\n")
	sb.WriteString("\t\t\tif actual != tc.expected {\n")
	sb.WriteString("\t\t\t\tt.Errorf(\"Input '%s' yielded '%s'; want '%s'\", tc.input, actual, tc.expected)\n")
	sb.WriteString("\t\t\t}\n")
	sb.WriteString("\t\t})\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	return ioutil.WriteFile(filePath, []byte(sb.String()), 0644)
}

func getErrorDescription(errType ErrorType) string {
	switch errType {
	case ErrUntransformedRawKey:
		return "Phím thô không biến đổi dấu (ddeer, vuwaf, thois)"
	case ErrSyllableDuplication:
		return "Lặp từ / lặp vần (nguoiười)"
	case ErrSwallowedChar:
		return "Nuốt ký tự đầu/giữa (õ thay vì gõ)"
	case ErrTonePlacement:
		return "Đổi vị trí đặt dấu (hòa vs hoà)"
	case ErrBackspaceDesync:
		return "Lệch số bước xóa lùi Backspace"
	case ErrOverRestoreFalsePositive:
		return "Khôi phục tiếng Anh nhầm"
	default:
		return "Lỗi chưa phân loại"
	}
}

func ensureDir(dir string) {
	_ = os.MkdirAll(dir, 0755)
}
